---
name: Deploy Temperature converter
on:
  push:
    branches:
      - master

jobs:
   check-file:
    runs-on: ubuntu-latest

    steps:
     - name: Checkout code
       uses: actions/checkout@v4

     - name: does index exist
       run: test -f index.html 

     - name: does style exist
       run: test -f style.css 

     - name: install vercel cli
       run: npm i -g vercel

     - name: Test Vercel authentication
       run: vercel whoami --token ${{ secrets.VERCEL_TEMPCONVERTER }}


     - name: Deploy
       run: vercel --token ${{secrets.VERCEL_TEMPCONVERTER}} --yes
  



   
   
    