---
name: Deploy Temperature converter
on:
  push:
    branches:
      - master

jobs:
   deploy:
    runs-on: ubuntu-latest

    steps:
     - name: Checkout code
       uses: actions/checkout@v4

     - name: Say hello
       run: echo "Hello"
        
     - name: deploy
       run: echo "Deploying"

    